services:
  mysql:
    image: mysql:8.0
    container_name: investment-mysql
    environment:
      MYSQL_DATABASE: investment_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7-alpine
    container_name: investment-redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:
